byte read_ram( void *sys, word address );
void write_ram( void *sys, word address, byte value );
byte read_ram_mirror( void *sys, word address );
void write_ram_mirror( void *sys, word address, byte value );
byte read_save_ram( void *sys, word address );
void write_save_ram( void *sys, word address, byte value );
byte read_prg_rom( void *sys, word address );
void write_ppu_control1( void *sys, word address, byte value );
void write_ppu_control2( void *sys, word address, byte value );
byte read_ppu_status( void *sys, word address );
void write_spr_ram_address( void *sys, word address, byte value  );
byte read_spr_ram_io( void *sys, word address );
void write_spr_ram_io( void *sys, word address, byte value  );
void write_scroll( void *sys, word address, byte value  );
void write_vram_address( void *sys, word address, byte value  );
byte read_vram_io( void *sys, word address );
void write_vram_io( void *sys, word address, byte value  );
void write_sprite_dma( void *sys, word address, byte value );
void write_vram_io( void *sys, word address, byte value  );
byte read_gamepad( void *sys, word address );
void write_gamepad( void *sys, word address, byte value );
byte read_unimplemented( void *sys, word address );
void write_unimplemented( void *sys, word address, byte value );